### ISSUE TITLE
if(pc_op != rti_pc )

### ISSUE THREAD

**Issue by iddq** [dg1yfe/sim68xx#1]
Hi Felix,

can you please tell me what is the purpose of this condition? thank you 73

https://github.com/dg1yfe/sim68xx/blob/4b0e97049822308677e35635acdaa5140d7b9525/src/arch/h6303/instr.c#L151

**Comment by dg1yfe** [comment]
Hi,

the purpose is to check if the address the CPU returns to after an IRQ is the same it would have executed next before entering the IRQ handler. It is there for debugging purposes, so one would have the possibility of spotting possible unintended changes in execution flow.
The warning will also trigger if the CPU performs an intended change of execution flow, e.g. when a task scheduler is implemented as timer ISR and a task switch was performed within the ISR.

**Comment by iddq** [comment]
Thanks, so if I understand correctly, this condition will be true if the return address has been changed by the interrupt handler, right?

**Comment by dg1yfe** [comment]
Yes - exactly
